### ISSUE TITLE
npm run prod, doesn't apply sass 

### ISSUE THREAD

**Issue by c29130811** [Ihatetomatoes/webpack-101-bootstrap#6]
Following a project you watched youtube.

The sass of react-bootstrap of tags in index.js does not apply.

However, it is applied in npm run dev.

Thank you for your comment.

**Comment by ronjb04** [comment]
I am having the same issue.. CSS is missing for the modal on run prod, but on dev its there.. where the modal shows up properly. Any solution for this yet?
